---
- name: Deploy OpenSearch
  kubernetes.core.helm:
    name: "{{ opensearch_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    chart_ref: opensearch/opensearch
    chart_version: "{{ opensearch_chart_version }}"
    release_namespace: "{{ opensearch_namespace_project_name }}"
    release_state: present
    create_namespace: true
    wait: true
    timeout: 10m
    values:
      replicas: 1
      config:
        opensearch.yml: |
          cluster.name: opensearch-cluster
          # Bind to all interfaces because we don't know what IP address will be assigned
          network.host: 0.0.0.0
          plugins.security.disabled: true
      extraEnvs:
      - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
        value: "Opensearch@admin@password@1234"
      persistence:
        enabled: true
        enableInitChown: false
