---
- name: Uninstall / remove DeathStarBench Hotel Reservation
  kubernetes.core.helm:
    name: "{{ deathstarbench_hotelreservation_app_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    chart_ref: roles/sample_applications/DeathStarBench/hotelReservation/helm-chart/hotelreservation
    release_namespace: "{{ deathstarbench_hotelreservation_app_namespace_project_name }}"
    state: absent
    wait: true

- name: Remove custom Security Context Constraints (SCC) for DeathStartBench Hotel Researvation on OpenShift
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    api_version: security.openshift.io/v1
    kind: SecurityContextConstraints
    name: dsb-hotel-reservation-scc
    state: absent
    wait: true
  when:
    - cluster_type is defined
    - cluster_type == "openshift" or cluster_type == "openshift_crc_local"

- name: Remove the namespace associated with the installation of DeathStarBench's Hotel Reservation
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ deathstarbench_hotelreservation_app_namespace_project_name }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
