---
- name: Apply tags to tasks within included file
  ansible.builtin.include_tasks:
    file: leverage_ingress.yaml
    apply:
      tags:
        - post_fault_injection
  tags:
    - post_fault_injection

- name: Apply tags to tasks within included file
  ansible.builtin.include_tasks:
    file: leverage_port_forwarding.yaml
    apply:
      tags:
        - post_fault_injection
  tags:
    - post_fault_injection

- name: Call the Topology APIs
  uri:
    url: "{{ topology_url }}/{{ item }}"
    method: GET
    return_content: yes
    body_format: json
    headers:
      Content-Type: "application/json"
  with_items:
    - "nodes"
    - "edges"
    - "graph"
    - "events"
  register: topology_responses
  retries: 10
  delay: 5
  until: topology_responses is succeeded
  tags:
    - post_fault_injection

- name: Ensure topology_information directory exists
  ansible.builtin.file:
    path: "/runner/topology_information"
    state: directory
  tags:
    - post_fault_injection
  when: run_uuid is defined and scenario_number is defined and run_number is defined

- name: Copy content to file(s)
  ansible.builtin.copy:
    content: "{{ item.content | to_json }}"
    dest: "/runner/topology_information/start_{{ item.item }}_{{now(utc=true,fmt='%Y-%m-%dT%H:%M:%S.%f')}}.json"
  with_items: "{{ topology_responses.results }}"
  tags:
    - post_fault_injection
  when: run_uuid is defined and scenario_number is defined and run_number is defined

- name: Upload structured-unstructured outputs to S3
  community.aws.s3_sync:
    bucket: "{{ s3_bucket_name_for_results }}"
    file_root: "/runner/topology_information"
    key_prefix: "{{ sre_agent_name__version_number }}/{{run_uuid}}/{{scenario_number}}/{{run_number}}/topology_information"
    region: "us-east-2"
  tags:
    - post_fault_injection
  when: run_uuid is defined and scenario_number is defined and run_number is defined
