- name: Deploy Saurabh's Kubernetes topology mapper
  kubernetes.core.helm:
    name: "{{ topology_mapper_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    chart_ref: tools/kubernetes-topology-mapper/charts/kubernetes-topology-mapper
    dependency_update: true
    release_namespace: "{{ topology_mapper_namespace_project_name }}"
    state: present
    wait: true
  tags:
    - post_fault_injection

- name: Pause for 5 minutes for the topology to be available
  ansible.builtin.pause:
    minutes: 5
  tags:
    - post_fault_injection
