- name: Deploy Saurabh's Kubernetes topology mapper (deprecated as wait 1 second)
  ansible.builtin.pause:
    seconds: 1
  tags:
    - post_fault_injection

- name: Pause for 5 minutes for the topology to be available (deprecated as wait 1 second)
  ansible.builtin.pause:
    seconds: 1
  tags:
    - post_fault_injection
